# Generated by Django 4.1.1 on 2022-10-07 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyaccount', '0007_alter_companyprofile_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_days', models.IntegerField(default=7)),
                ('price', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('Free', 'free'), ('Paid', 'paid')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_subscription', to='companyaccount.companyprofile')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.membership')),
            ],
        ),
    ]
