# Generated by Django 4.1.1 on 2022-10-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_payment_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
    ]
