# Generated by Django 4.1.1 on 2022-10-07 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyaccount', '0007_alter_companyprofile_company_logo'),
        ('subscription', '0005_remove_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysubscription',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_subscription', to='companyaccount.companyprofile'),
        ),
    ]
