# Generated by Django 4.1.1 on 2022-10-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_alter_companysubscription_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysubscription',
            name='active',
        ),
    ]
