# Generated by Django 4.1.1 on 2022-10-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_remove_companysubscription_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysubscription',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
