# Generated by Django 4.1.1 on 2022-10-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_alter_companysubscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysubscription',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
