# Generated by Django 4.1.1 on 2022-10-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='experience',
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='max_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='min_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
