# Generated by Django 4.1.1 on 2022-10-18 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_remove_savedjobs_user_savedjobs_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='candidate_image',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
    ]
