# Generated by Django 4.1.1 on 2022-10-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='No_of_openings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'full time'), ('part-time', 'Part Time'), ('temporary', 'Temporary'), ('contract', 'Contract'), ('freelance', 'Freelance')], max_length=50),
        ),
    ]
