# Generated by Django 4.1.1 on 2022-09-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_jobmodel_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='published_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
