# Generated by Django 4.1.1 on 2022-10-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='work_type',
            field=models.CharField(choices=[('Work From Home', 'Work from Home'), ('Work From Office', 'Work from Office'), ('Hybrid', 'Hybrid')], max_length=50),
        ),
    ]
