# Generated by Django 4.1.1 on 2022-10-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_jobmodel_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'full time'), ('Part Time', 'Part Time'), ('Temporary', 'Temporary'), ('Contract', 'Contract'), ('Freelance', 'Freelance')], max_length=50),
        ),
    ]
