# Generated by Django 4.1.1 on 2022-10-10 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_status', models.CharField(choices=[('Accepted', 'accepted'), ('Rejected', 'rejected')], default='Applied', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('processed_date', models.DateTimeField()),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.jobmodel')),
            ],
        ),
    ]
