# Generated by Django 4.1.1 on 2022-10-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lateducation',
            name='study_country',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='languages_known',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='summary',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
