# Generated by Django 4.1.1 on 2022-10-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_candidateprofile_skills_delete_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_status',
            field=models.CharField(choices=[('Applied', 'applied'), ('Accepted', 'accepted'), ('Rejected', 'rejected')], default='Applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='processed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
