# Generated by Django 4.1.1 on 2022-10-14 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_alter_jobapplication_applied_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjobs',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidateprofile'),
        ),
    ]
