# Generated by Django 4.1.1 on 2022-10-14 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyaccount', '0004_remove_companyprofile_country_code_and_more'),
        ('candidate', '0004_alter_jobapplication_applied_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyaccount.companyprofile'),
        ),
    ]
