# Generated by Django 4.1.1 on 2022-10-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_savedjobs_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedjobs',
            name='user',
        ),
    ]
