# Generated by Django 4.1.1 on 2022-09-24 15:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(error_messages={'unique': 'This email already exists. Already a member?'}, max_length=254, unique=True)),
                ('is_mail_verified', models.BooleanField(default=False)),
                ('dob', models.DateField(null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('profile_pic', models.ImageField(null=True, upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
