# Generated by Django 4.1.1 on 2022-09-24 10:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(default='', null=True)),
                ('fb', models.URLField(default='', null=True)),
                ('instagram', models.URLField(default='', null=True)),
                ('linkedin', models.URLField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='companyimages', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
                ('company_description', models.CharField(max_length=500, null=True)),
                ('industry', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(choices=[('full-time', 'full-time'), ('part-time', 'part-time'), ('intern', 'intern')], max_length=100)),
                ('founded', models.PositiveIntegerField(null=True)),
                ('team_size', models.CharField(choices=[('0-100', '0-100'), ('100-500', '100-500'), ('500-1000', '500-1000'), ('1000+', '1000+')], max_length=10)),
                ('company_email', models.EmailField(error_messages={'unique': 'A user with this email already exist'}, max_length=254, unique=True)),
                ('is_mail_verified', models.BooleanField(default=False)),
                ('phone', models.PositiveIntegerField(null=True)),
                ('location', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=250, null=True)),
                ('country_code', models.PositiveIntegerField(null=True)),
                ('social_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyaccount.socialprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
