# Generated by Django 4.1.1 on 2022-10-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyaccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='is_mail_verified',
            field=models.BooleanField(default=False),
        ),
    ]
