# Generated by Django 4.1.1 on 2022-09-28 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyaccount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='type',
        ),
        migrations.AlterField(
            model_name='company',
            name='social_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_pro', to='companyaccount.socialprofile'),
        ),
    ]
