# Generated by Django 4.1.1 on 2022-10-04 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyaccount', '0002_companyprofile_is_mail_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='social_profile',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
    ]
