# Generated by Django 4.1.1 on 2022-09-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyaccount', '0002_remove_company_type_alter_company_social_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='social_profile',
        ),
    ]
