# Generated by Django 4.1.1 on 2022-10-06 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyaccount', '0003_remove_companyprofile_social_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_logo',
            field=models.ImageField(blank=True, default='home/images/company_logo.jpg', null=True, upload_to='company_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
    ]
