# Generated by Django 4.1.1 on 2022-09-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyaccount', '0003_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
