# Generated by Django 4.1.1 on 2022-09-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyaccount', '0004_alter_company_company_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user',
            new_name='users',
        ),
    ]
