# Generated by Django 4.1.1 on 2022-10-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_payment_payment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_number',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
