# Generated by Django 4.1.1 on 2022-10-19 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_payment_payment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_number',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
